### PR TITLE
Explained how to obtain push certificate

### PR DESCRIPTION
**Pull request by infostreams**
Adapted from https://gist.github.com/ndfred/3983259

### CODE REVIEW

**Comment by infostreams** [comment]
It is not easy or straight forward to set this up, and the only documentation we have so far is a dead link to an outdated guide at apple.com.

**Comment by dwightwatson** [comment]
Why don't we just update the broken link to the Apple docs? 

Is it necessary for a package to provide instructions to generate tokens if the Apple docs provide proper guidance on how to do it? I haven't done it myself in a while but does it no longer provide a `.pem` certificate?

**Comment by infostreams** [comment]
Can you find the link? Because I can't.

**Comment by dwightwatson** [comment]
[This looks like the generic push notification guide](https://help.apple.com/xcode/mac/current/#/devdfd3d04a1) and [this looks like the certificate specific guide](https://help.apple.com/developer-account/#/dev82a71386a). What do you think of these?

**Comment by infostreams** [comment]
The second link explains how to get the p12 certificate, but you can't just connect with the p12 certificate.

**Comment by dwightwatson** [comment]
Do you know if that's a recent development or what the difference between `pem`/`p12` is?

Happy to merge this in, but perhaps we need to consider supporting `p12` out of the box if it's a newer standard.

**Comment by infostreams** [comment]
No, I have no idea what the difference is. For me it's just a series of magic incantations I need to do to get the thing to work. I adjusted the text so that it includes links to the Apple documentation, and kept the 3 or 4 last steps that are necessary to convert from Apple's output certificate (the p12 file) to the .pem file that we require.

Agree that it would be helpful to just use the p12 file, but I have no idea how to even approach that. I think if we want that you would need to go knocking on [this door](https://github.com/zendframework/ZendService_Apple_Apns/blob/master/src/Apns/Client/AbstractClient.php), somehow.

**Comment by dwightwatson** [comment]
Cool, I agree that it does sound like it will be difficult. This is a great step in the right direction in the meantime. Thanks for taking the time to put this together.

**Pull request merged**
