### PR TITLE
Add support for Laravel 6.0

### PR DESCRIPTION
**Pull request by dwightwatson**
Add support for Laravel 6.0 and match PHP version constraint.

### CODE REVIEW

**Comment by infostreams** [comment]
This broke support for all versions of Laravel that are not 6.0 or later. Given that the code itself is almost unchanged that seems a bit unnecessary. Can we solve this [the way that laravel-fcm-notification added 6.0 support](https://github.com/benwilkins/laravel-fcm-notification/pull/46/commits/3ddf5bd2f68755e8b5e2ca371c2b43e1fac2c142#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R20)? Basically allowing something like 5.6 and up, and then also signalling that you can use it with 6.0?

**Comment by infostreams** [comment]
Additionally, I think the version number should have been increased because it's a breaking change. There's no easy/straight-forward/obvious way to install the version that doesn't have this breaking change.

**Comment by dwightwatson** [comment]
As I understand semantic versioning that prior to hitting version 1.0 that any release can be considered breaking. Also it shouldn't have broken support for any versions prior to Laravel 6.0 because the previous tag `0.4.0` is still available to be installed.

You're correct in that there is nothing specific that makes the package incompatible with either version but breaking support off separately means we have a clean slate to support the (now semantic) 6.0 release going forward without having to worry about any prior versions.

I'm still curious as to why this *broke* for you as it really shouldn't - what version constraint do you have in your `composer.json` file?

**Comment by infostreams** [comment]
I just typed `composer require laravel-notification-channels/apn` and then it wanted to install the latest version, which is Laravel 6 only.

**Comment by dwightwatson** [comment]
Ah you're right - that's frustrating. Maybe Composer only considers stable tagged releases when trying to find a previous version that matches. Would adding Laravel 5.* specific installation instructions to the README be a reasonable solution?

**Comment by infostreams** [comment]
Well, to be honest I don't think there's a good technical reason to specifically exclude Laravel 5.* from installing this package. The changes between 5 and 6 are not that significant. My policy here would be to keep Laravel 5.6/5.7/5.8 in while it still works, but without offering support. You're excluding a huge installed base (basically all currently existing Laravel projects) for no good reason – but alas, since it's not my package that's not my call ¯\_(ツ)_/¯

But to answer your question: yes, a specific 'what to do if you have Laravel 5' section in the documentation would help.

**Comment by dwightwatson** [comment]
My intention isn't to exclude anyone, but that you use version `0.4.x` if you're running Laravel 5.x and later versions to support Laravel 6.x. It was my understanding that Composer would install the latest supported version automatically but it seems that doesn't work pre-1.0.

I suppose the most correct way to fix this would be to tag the latest 5.x compatible version as 1.0.0 and then tag the latest 6.x compatible version as 2.0.0 and then it should be automatically installable on both. Unfortunately our syncing with Packagist is currently broken so tagging those won't work. 

What I'll do now is open a ticket to fix the Packagist syncing so we can get tagging working again and also update the docs to include Laravel 5.x installation instructions. Once we're back in business we can look at tagging each release properly.

**Comment by infostreams** [comment]
Sounds like a plan. Not sure if Composer automatically figures out which version it has to install in case you have Laravel 5, but happy to take your word for it. Thanks!

**Pull request merged**
