### PR TITLE
Replace Zend with Pushok to support p8 authentication

### PR DESCRIPTION
**Pull request by dwightwatson**
This represents a substantial rewrite of the package in order to support the more recent .p8 certificate authentication. We drop the Zend dependency - which hasn't seen much activity in a while - in favour of a newer package called Pushok.

In this first pass, I've stripped a lot of fat. 

* `urlArgs` on the message have been removed as I can't find the equivalent feature in Pushok.
* Pushok looks after the connection instead of us having to open/close it following every push. We did this because we were having issues when a token had expired, but we don't know if this issue will persist.
* I've removed event dispatching - I don't know how much it's used, and will bring it back if it's asked for. I suspect we can just dispatch the whole notification result, instead of just failures.
* I've removed the feedback service because similar functionality doesn't appear to be provided anymore - perhaps the client response will contain the required information?

Open to feedback here - still need to do more cleanup, and actually sort out the test suite.

Relevant #29

### CODE REVIEW

**Comment by dwightwatson** [comment]
If you want to test this, you'll need to adjust your `broadcasting` configuration.

```php
'connections' => [
    'apn' => [
         'environment' => ApnChannel::PRODUCITON,
         'key_id' => '',
         'team_id' => '',
         'app_bundle_id' => '',
         'private_key_path' => '',
         'private_key_secret' => '',
    ],
],
```

**Comment by zek** [comment]
Weirdly I do get DeviceTokenNotForTopic error. Before that I was able to sent notification via this library. I have an app in testflight and it works like a charm. But right now I cant send any notification

**Comment by zek** [comment]
@dwightwatson OK I am able to fix the problem. I use voip push notifications therefore I needed to use app_bundle_id as com.app.voip.

**Comment by zek** [comment]
So I believe we could merge this PR.

**Comment by zek** [comment]
We also need ApnCredentials class.  Right now credentials method is not working

**Comment by dwightwatson** [comment]
What do you need it for? The ApnCredentials class was removed intentionally.

**Comment by buttjer** [comment]
apns-priority is needed for silent notification and its not supported by zend but by pushok. 👍

**Comment by simensen** [comment]
I'm super interested in using the next version of this package w/ pushok. Is there a lot of work still to be done on it? Wondering if it is safe for me to start dev using `dev-develop` for the time being or if that is just not going to work at all...

**Comment by dwightwatson** [comment]
Unfortunately I don’t have a .p8 key to test with currently, so while this *should* work I haven’t been able to verify it.

If this PR does work it’s what I intend to be the next major version. 

If you can test with this branch please let me know if and what issues you run into and I’ll work to resolve them. Otherwise if it’s all good I’ll consider merging and tagging a new major release.

**Pull request merged**
